### ISSUE TITLE
how to build on windows

### ISSUE THREAD

**Issue by Auditor1234** [IRCAD/sight#8]
Can someone tell me how to build this project on Windows 11 and Visual Studio 2019? The detailed install instructions web page always report 502. 

Thank you very much!

**Comment by aancel** [comment]
Hello,

Thanks for reporting the issue regarding the documentation !    
Regarding building, I propose you to try and build the documentation from sources.    
It is available at this url: https://git.ircad.fr/sight/sight-doc

In order to build it:
- Clone the repo above using git
- You will have to have python installed on your computer. I'd suggest installing [scoop](https://scoop.sh/) to manage additional dependencies.
- You will also need the `make` tool
- And some python libraries: `sphinx-rtd-theme` & `sphinx_tabs`
- Then issueing `make html` inside your local clone should allow you to build the documentation in the `_build` subfolder

;TLDR for building on Windows (assuming scoop is already installed)
```
scoop install git make python graphviz
pip install sphinx-rtd-theme sphinx_tabs

git clone https://git.ircad.fr/sight/sight-doc

cd sight_doc
make html
```

Let us know if you manage to build the documentation !     
And don't hesitate to come back afterwards if you have issues building Sight on Windows

**Comment by Auditor1234** [comment]
Thank you for your timely reply.

I have got the html documentations according to your guides.

Best regards!

**Comment by aancel** [comment]
Great news !    
I suggest that you keep using scoop to install additional packages required to build.     
I'll leave this issue open in case you have additional issues building the library.    
Don't hesitate to close it if you manage to successfully build it !

**Comment by Auditor1234** [comment]
I am sorry to bother you again.

As I finished the building stage, and executed the file `Dev/Build/Debug/bin/activityTest.exe`. 
While a box pops up which reminds that(I have set CMAKE_BUILD_TYPE=Debug):
> cppunitd.dll not found, execution will be terminted.
> The problem may be fixed by reinstalling the program.

Then I add `<Source_Dir>\sight-vcpkg-0c1939bb\installed\x64-windows\debug\bin` to my environment variable `Path`.
It seems worked.
I want to ask is it right?

**Comment by aancel** [comment]
No problem !
Regarding the issue you are encoutering, yes it is right as the dll must be present in the `Path` variable for the libraries to be detected on Windows.     
Please also notice that for each `.exe` file in the bin folder, there is also a `.bat` file which is written from a template and takes care of setting up the path variable for you. This way you don't have to set it manually.
Generally we rather use those `.bat` files than `.exe`

**Comment by Auditor1234** [comment]
Thanks!
I think my issues have been soloved.
Your advice is very useful.
